= MiAZ, a Personal Document Organizer

== Use case

The main goal is to organize family documentation.

This project is based solely in my own experience and for my own necesities which can fit yours, or not.

In any case, it tries to help organizing the day to day paperwork such as invoices, letters, and any document sent by/sent to any person (legal entity or natural)

With this in mind, MiAZ uses its own filename convention in order to manage the repository of documents.


== File name convention

All documents managed by MiAZ are renamed following this name convention consisting on 7 fields:

`{timestamp}-{country}-{group}-{subgroup}-{sentby}-{purpose}-{concept}-{sentto}.{extension}`

* _Timestamp_: with format: %Y%m%d (eg.: 20221119)
* _Country_: ISO-3166 Alpha-2 code (eg.: ES)
* _Group_: root category to which many documents belong to with a similar purpose. (eg.: HOUSE, EDU, BANKS, WORK, ADM)
* _Subgroup_: a distinct group within a group (Eg. for HOUSE: HEATING, WATER, INSURANCE, ELECTRICITY, etc...)
* _Purpose_: reason (eg.: INFO, REQUEST, INVOICE, STATEMENT, etc...)
* _SentBy_: the (legal or natural) person sending the document
* _Concept_: the details (eg.: invoice number, flight number, etc...)
* _SentTo_: the (legal or natural) person receiving the document
* _Extension_: the extension/media format of the document


[NOTES]
====
* Each field is separated by a hyphen (`-`). Only 6 hyphens are allowed. Extra hyphens found in a field are automatically converted to underscores (`_`)
* Country code is important in case that the family has ties with others countries apart from the one where they reside)
* The timestamp format helps to sort documents easily in a file browser
* SentBy/SentTo fields are stored as a key/value where key is a identifier (eg.: person initials) and value is the full name (eg.: Company or person name)
====


== Directory Structure

The user has to choose an empty _root_ directory (eg.: $HOME/Documents/MiAZ) where the application can deploy the rest of files and directories.

At present, it uses 2 directories:

* _conf_: this directory holds the repository configuration
* _repo_: the most important directory, as it will store all files. As it could be thousands of them from several years, each document will be stored in the proper year subdirectory.

.Example:
----
$HOME/Documents/MiAZ
├── conf
├── repo
----

== Current status

This project is an early stage of development. Working with the most important feature: repository documentation an file renaming.


