#~ subdir('conf')
#~ subdir('icons')

install_subdir('conf', install_dir: join_paths(get_option('datadir'), meson.project_name(), 'resources' ))
install_subdir('icons', install_dir: join_paths(get_option('datadir'), meson.project_name(), 'resources' ))
install_subdir('plugins', install_dir: join_paths(get_option('datadir'), meson.project_name(), 'resources' ))
