#!/bin/bash
# Build a Windows portable executable and optional NSIS installer for MiAZ.
#
# Uses PyInstaller to bundle the Python app and GTK4 runtime into a
# self-contained directory, then optionally wraps it with an NSIS installer.
#
# ── Prerequisites ─────────────────────────────────────────────────────────────
# This script must run on Windows under MSYS2/MinGW64 (or a Windows CI runner
# with MSYS2 installed). Cross-compilation from Linux is NOT supported by
# PyInstaller.
#
#   # Install GTK4 + Python bindings via MSYS2:
#   pacman -S mingw-w64-x86_64-python \
#             mingw-w64-x86_64-python-gobject \
#             mingw-w64-x86_64-gtk4 \
#             mingw-w64-x86_64-libadwaita \
#             mingw-w64-x86_64-python-pip
#   pip install pyinstaller
#
#   # Optional — NSIS installer (.exe setup wizard):
#   pacman -S mingw-w64-x86_64-nsis
#
# NOTE: Libadwaita has limited Windows support. Some Adw.* widgets may not
#       render correctly outside a Linux/GNOME session.
#
# Run from anywhere; the script locates the repo root automatically.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# ── helpers ──────────────────────────────────────────────────────────────────
log()  { echo "[win] $*"; }
die()  { echo "[win] ERROR: $*" >&2; exit 1; }

require() {
    for cmd in "$@"; do
        command -v "$cmd" &>/dev/null || die "Required tool not found: $cmd"
    done
}

# ── version ──────────────────────────────────────────────────────────────────
VERSION=$(grep -m1 "version" "$REPO_ROOT/meson.build" \
    | sed "s/.*version.*: *'\([^']*\)'.*/\1/")
[[ -n "$VERSION" ]] || die "Could not read version from meson.build"
log "Version: $VERSION"

APP_NAME="MiAZ"
NAME="miaz"
OUTPUT_DIR="$REPO_ROOT/builddir_win"

# ── preflight ─────────────────────────────────────────────────────────────────
require python3 pyinstaller

log "Repo root:  $REPO_ROOT"
log "Output dir: $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# ── generate PyInstaller spec via Python (avoids shell-escaping complexity) ──
SPEC_FILE="$OUTPUT_DIR/${NAME}.spec"
log "Writing PyInstaller spec: $SPEC_FILE"

python3 - "$REPO_ROOT" "$OUTPUT_DIR" "$VERSION" "$APP_NAME" <<'PYEOF'
import sys, os

root     = sys.argv[1]
out_dir  = sys.argv[2]
version  = sys.argv[3]
app_name = sys.argv[4]

# Locate the best available icon
icon = None
for candidate in [
    os.path.join(root, 'data', 'docs', 'brand', 'io.github.t00m.MiAZ-brand.ico'),
    os.path.join(root, 'data', 'docs', 'brand', 'io.github.t00m.MiAZ-brand.png'),
]:
    if os.path.exists(candidate):
        icon = candidate
        break

icon_line = f"    icon={icon!r}," if icon else ""

# Collect data dirs that actually exist
datas = []
for src, dest in [
    (os.path.join(root, 'data'),                          'data'),
    (os.path.join(root, 'data', 'resources', 'plugins'), 'data/resources/plugins'),
    (os.path.join(root, 'po'),                            'po'),
]:
    if os.path.exists(src):
        datas.append(f"        ({src!r}, {dest!r}),")

datas_block = "\n".join(datas)

spec = f"""\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by scripts/packaging/win/create_exe.sh — do not edit.
from pathlib import Path

ROOT = Path({root!r})

a = Analysis(
    [str(ROOT / 'MiAZ' / 'miaz.py')],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
{datas_block}
    ],
    hiddenimports=[
        'gi',
        'gi.repository.Gtk',
        'gi.repository.Adw',
        'gi.repository.GLib',
        'gi.repository.Gio',
        'gi.repository.GObject',
        'gi.repository.Pango',
        'gi.repository.cairo',
        'MiAZ',
        'MiAZ.miaz',
        'MiAZ.backend',
        'MiAZ.frontend',
        'MiAZ.frontend.desktop',
        'MiAZ.frontend.desktop.widgets',
        'MiAZ.frontend.console',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='{app_name}',
    debug=False,
    strip=False,
    upx=True,
    console=False,
{icon_line}
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='{app_name}',
)
"""

spec_path = os.path.join(out_dir, 'miaz.spec')
with open(spec_path, 'w') as fh:
    fh.write(spec)
print(f"[win] Spec written to {spec_path}")
PYEOF

# ── run PyInstaller ───────────────────────────────────────────────────────────
log "Running PyInstaller ..."
pyinstaller "$SPEC_FILE" \
    --distpath "$OUTPUT_DIR/dist" \
    --workpath "$OUTPUT_DIR/build" \
    --noconfirm

# On Windows/MSYS2 PyInstaller produces APP_NAME.exe; on Linux it has no extension.
if [[ "$(uname -s)" =~ ^(MSYS|MINGW|CYGWIN) ]]; then
    EXE_EXT=".exe"
else
    EXE_EXT=""
fi
EXE_PATH="$OUTPUT_DIR/dist/$APP_NAME/$APP_NAME$EXE_EXT"
[[ -f "$EXE_PATH" ]] || die "PyInstaller finished but $EXE_PATH not found."
log "Executable: $EXE_PATH"

# ── optional NSIS installer ───────────────────────────────────────────────────
if ! command -v makensis &>/dev/null; then
    log ""
    log "makensis not found — skipping .exe installer."
    log "Portable build is at: $OUTPUT_DIR/dist/$APP_NAME/"
    log ""
    log "To create an NSIS installer, install NSIS and re-run:"
    log "  MSYS2:   pacman -S mingw-w64-x86_64-nsis"
    log "  Windows: https://nsis.sourceforge.io/Download"
    exit 0
fi

log "makensis found — building NSIS installer ..."
NSI_FILE="$OUTPUT_DIR/${NAME}.nsi"
INSTALLER_OUT="$OUTPUT_DIR/${APP_NAME}-${VERSION}-setup.exe"
DIST_DIR="$OUTPUT_DIR/dist/$APP_NAME"

python3 - "$VERSION" "$DIST_DIR" "$INSTALLER_OUT" "$APP_NAME" <<'PYEOF'
import sys, os

version       = sys.argv[1]
dist_dir      = sys.argv[2]
installer_out = sys.argv[3]
app_name      = sys.argv[4]
nsi_path      = os.path.join(os.path.dirname(installer_out), f'{app_name.lower()}.nsi')

nsi = f"""\
; NSIS installer script — auto-generated by scripts/packaging/win/create_exe.sh
Unicode True
SetCompressor lzma

!define APP_NAME      "{app_name}"
!define APP_VERSION   "{version}"
!define APP_PUBLISHER "Tomás Vírseda"
!define APP_URL       "https://github.com/t00m/MiAZ"
!define DIST_DIR      "{dist_dir}"
!define INSTALLER_OUT "{installer_out}"

Name "${{APP_NAME}} ${{APP_VERSION}}"
OutFile "${{INSTALLER_OUT}}"
InstallDir "$PROGRAMFILES64\\${{APP_NAME}}"
InstallDirRegKey HKLM "Software\\${{APP_NAME}}" "Install_Dir"
RequestExecutionLevel admin

Page directory
Page instfiles
UninstPage uninstConfirm
UninstPage instfiles

Section "Install"
    SetOutPath "$INSTDIR"
    File /r "${{DIST_DIR}}\\*.*"
    WriteRegStr HKLM "Software\\${{APP_NAME}}" "Install_Dir" "$INSTDIR"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${{APP_NAME}}" \\
        "DisplayName" "${{APP_NAME}}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${{APP_NAME}}" \\
        "UninstallString" '"$INSTDIR\\Uninstall.exe"'
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${{APP_NAME}}" \\
        "Publisher" "${{APP_PUBLISHER}}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${{APP_NAME}}" \\
        "DisplayVersion" "${{APP_VERSION}}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${{APP_NAME}}" \\
        "URLInfoAbout" "${{APP_URL}}"
    CreateDirectory "$SMPROGRAMS\\${{APP_NAME}}"
    CreateShortcut "$SMPROGRAMS\\${{APP_NAME}}\\${{APP_NAME}}.lnk" "$INSTDIR\\${{APP_NAME}}.exe"
    CreateShortcut "$DESKTOP\\${{APP_NAME}}.lnk" "$INSTDIR\\${{APP_NAME}}.exe"
    WriteUninstaller "$INSTDIR\\Uninstall.exe"
SectionEnd

Section "Uninstall"
    RMDir /r "$INSTDIR"
    Delete "$SMPROGRAMS\\${{APP_NAME}}\\${{APP_NAME}}.lnk"
    RMDir "$SMPROGRAMS\\${{APP_NAME}}"
    Delete "$DESKTOP\\${{APP_NAME}}.lnk"
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${{APP_NAME}}"
    DeleteRegKey HKLM "Software\\${{APP_NAME}}"
SectionEnd
"""

with open(nsi_path, 'w', encoding='utf-8') as fh:
    fh.write(nsi)
print(f"[win] NSI script written to {nsi_path}")
PYEOF

makensis "$NSI_FILE"

[[ -f "$INSTALLER_OUT" ]] || die "makensis finished but $INSTALLER_OUT not found."
log "Done: $INSTALLER_OUT"
log ""
log "Install on the target Windows machine with:"
log "  ${APP_NAME}-${VERSION}-setup.exe"
